### ISSUE TITLE
site-seedu attribute in build.gradle

### ISSUE THREAD

**Issue by nianfei97** [nusCS2113-AY1819S1/forum#102]
In the DG of AB4 (https://se-edu.github.io/addressbook-level4/DeveloperGuide.html#Docs-SiteWideDocSettings), it is written that the attribute `site-seedu` should be defined if our project is an "official SE-EDU project". This seems to imply that this attribute should not be set as our project is not "official".

However, in the `build.gradle` file, the following is written as a comment:

> // delete this line if your project is not a fork (not a SE-EDU project)

which seems to imply that the attribute should be set, as our project is indeed a fork of AB4.

Should this attribute be set or not in our final version of the project?

**Comment by okkhoy** [comment]
Leave the value unset. Setting that generates a se-edu header.

**Comment by nianfei97** [comment]
Got it!
