### ISSUE TITLE
No url found for submodule path 'main' in .gitmodules error when running travis

### ISSUE THREAD

**Issue by rajdeepsh** [nusCS2113-AY1819S1/forum#104]
Hi guys, I was doing a [PR](https://github.com/CS2113-AY1819S1-T13-4/main/pull/135) and encountered this error.

![image](https://user-images.githubusercontent.com/35727146/48088640-75adb180-e23d-11e8-8f73-78607aec773d.png)

Does anyone know how to solve this ? As I have not encountered this before. I do however remember adding a url to a submodule before as the GUI was prompting me to do so and would not let me check out to another branch until I did it some time back. I did not think it would matter at that time. This is the most probable reason, however I not too sure on how to resolve it. 

![image](https://user-images.githubusercontent.com/35727146/48088862-0d130480-e23e-11e8-9d1a-e716febb0796.png)

**Comment by yamgent** [comment]
Try removing the `.gitmodules` file in your PR and push again.

**Comment by rajdeepsh** [comment]
> Try removing the `.gitmodules` file in your PR and push again.

@yamgent yes that seems to resolve the issue, thanks !
