### ISSUE TITLE
Converting html to pdf

### ISSUE THREAD

**Issue by rajdeepsh** [nusCS2113-AY1819S1/forum#112]
Hi 

When converting html to pdf using the `ctrl-p -> save as pdf` method on **chrome**, it seems as though all the url's are shown along with the links. Is this considered acceptable ? If not, what converter would you recommend using ?

![image](https://user-images.githubusercontent.com/35727146/48337940-554b8000-e69f-11e8-9e4e-31f86ccec62e.png)

**Comment by QzSG** [comment]
Facing the same issue too, also a little off tangent, can the submitted pdf of portfolio be different from the online one hosted on github pages? (ie such as removing certain images after converting to pdf to fit page limit ?)

**Comment by yamgent** [comment]
> When converting html to pdf using the `ctrl-p -> save as pdf` method on **chrome**, it seems as though all the url's are shown along with the links.

A solution to get rid of the URLs can be found [here](https://github.com/nus-cs2103-AY1819S1/forum/issues/172#issuecomment-437681359).

**Comment by rajdeepsh** [comment]
> Facing the same issue too, also a little off tangent, can the submitted pdf of portfolio be different from the online one hosted on github pages? (ie such as removing certain images after converting to pdf to fit page limit ?)

@QzSG I'll leave this issue open for your qn.

**Comment by okkhoy** [comment]
If the images are not adding "too much" additional value, you can remove them and convert to pdf (or remove after converting to pdf) to fit into the page limit. 
E.g., removing screenshots is OK; but removing the **only UML** diagram is NOT OK!
@QzSG @rajdeepsh

**Comment by QzSG** [comment]
@rajdeepsh feel free to close

**Comment by leegengyu** [comment]
@okkhoy Sorry for the late question, but we were wondering if we removed all links in our PDF version of PPP as per the solution given above, would that be alright?

Would like to clarify this matter because our RepoSense link would also not show up in the PDF.

Thank you!

**Comment by okkhoy** [comment]
@leegengyu we will need links to your code, else for testers it will be difficult to access your code. (rather it will be too much work)

**Comment by leegengyu** [comment]
Noted, thank you for your reply! 👍

**Comment by yamgent** [comment]
Do note that while the solution hides the URLs, the links themselves are still clickable in the PDF file.
