### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by jinyao-lee** [nusCS2113-AY1819S1/forum#19]
Hi,

If I have an existing pull request up on the upstream fork, but I have made updates to my own repo (after a PR was submitted) and want to have my latest changes updated to the pull request, do I have to close my current PR and create a new one? Or will the existing PR detect my latest commits and update them accordingly?

Thanks!

**Comment by QzSG** [comment]
Commits pushed to your topic branch related to the pull request will update the pull request accordingly

**Comment by jinyao-lee** [comment]
Noted. Thanks
