### ISSUE TITLE
Requesting use of .csv file

### ISSUE THREAD

**Issue by speezy37** [nusCS2113-AY1819S1/forum#22]
Hello, 

My team is planning to implement a product with a wide user base. Hence, we are planning to use .csv files for the following reasons:
1. A single csv file to replace multiple .txt files
2. Reduce complexity in managing several .txt files
3. Simulating an online database

Could you advise on this matter?

Thank you.

**Comment by okkhoy** [comment]
First, I see a potential problem with this:
> My team is planning to implement a product with a wide user base. 

We want you to make the product for a specific user profile. If the profile encompasses a large user base, then we are OK.

Not too sure what you mean by 
> 3. Simulating an online database.

As per the constraints, no DBMS to store the data. If your approach involves using queries like DBMS, I wouldn't encourage it.

I don't see a problem with CSV as it is still within the constraints that the file should be human-editable.
