### ISSUE TITLE
AB4: Error when running Checkstyle for whole project. Error message: "The scan failed due to an error - please see the event log for more information"

### ISSUE THREAD

**Issue by alexiscatnip** [nusCS2113-AY1819S1/forum#34]
**What is the problem:**
On AB4, if you run checkstyle for whole project, it will scream about an error: "The scan failed due to an error - please see the event log for more information". Event log pasted below; it complains about the java runtime's version.

I suspect its because intellij uses an older version of JDK (older than the project settings's JDK 9) to run the checkstyle... or something like that.

**What I tried to solve this**
I tried to solve the issue by forcing intellij to boot with JDK 9.0, instead of the default JD SDK 1.8.0 (switch boot JDK command in Intellij). But this only made all my project files disappear! I ran gradlew processResources, which was successful, but did not help.

**How to replicate problem:**
I have intellij set up with:
- JDK 9 in project settings
- Intellij is booting with the default JB SDK 1.8.0 (Inside Intellij window > Help > About)
- Have Run 'All Tests' before at least once

**Event log:**
4:58 PM	Unexpected Exception Caught
				The scan failed due to an exception: An error occurred while scanning a file.
				Root cause:
				guitests/guihandles/exceptions/NodeNotFoundException has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
				java.lang.UnsupportedClassVersionError: guitests/guihandles/exceptions/NodeNotFoundException has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

				at java.lang.ClassLoader.defineClass1(Native Method)
...

**Comment by damithc** [comment]
Are you able to run checkstyle outside of intellij, using gradle?

**Comment by alexiscatnip** [comment]
The issue seems to have resolved itself... :slightly_frowning_face:
