### ISSUE TITLE
How to setup coverage for AB3?

### ISSUE THREAD

**Issue by px1099** [nusCS2113-AY1819S1/forum#46]
- While setting up coverage for our project, we noticed that our build.gradle and travis.yml is different from the guide written for AB4. How can we work around to set up coverage for AB3?
- Also, we could not view the guiding images on [the coverage setup guide webpage on AB4](https://github.com/nusCS2113-AY1819S1/addressbook-level4/blob/master/docs/UsingCoveralls.adoc). Is there any problem with the images?

**Comment by 0WN463** [comment]
For point 1, the way I did it was just look at the one from AB4 and adapt it into AB3.
For point 2, I think that is the problem with GitHub right this instant, cause other images on GitHub are not showing properly (for me at least) at this moment either
