### ISSUE TITLE
RepoSense

### ISSUE THREAD

**Issue by sijieg** [nusCS2113-AY1819S1/forum#56]
Hi,

I have followed the steps in the userguide for RepoSense and used the template in our CS2113 website to "Provide Data Using a json Config File". 

The issue here for me is that whenever i run the command "java -jar RepoSense.jar -repo " on my local repo(i.e path to AB4 file), it does not work as it will return "addressbook-level4_master has no authors specified, using all authors by default." However, it does work if i run the command on my main repo (i.e URL.git)

Does anyone know if im doing the right thing on my local repo? Thanks.

**Comment by eugenepeh** [comment]
Hi @sijieg ,

Thanks for sharing with us of your concerns on behalf of the RepoSense team.

Could you provide us with more details, such as screenshots and the url to your team repository.
Note that your the local path has to be your repository root, e.g. `C:\Users\user\Desktop\main`, and the json Config file **must** be committed to the git repository.

Thank you.

Best regards,
Eugene

**Comment by sijieg** [comment]
Hi Eugene,
Attached is the screenshot to my team repo. 
![image](https://user-images.githubusercontent.com/35765034/47256879-3fd8a100-d4b9-11e8-8c5e-f85a7dedc005.png)

The URL is https://github.com/CS2113-AY1819S1-T13-5/main
The local path that I used is `C:\Users\SJ\IdeaProjects\addressbook-level4` and the config json file 
has already been committed in both our team repo and my own repo.

Thank you!

**Comment by QzSG** [comment]
@sijieg I tried cloning your team repo you linked and running RepoSense on local cloned folder, seems to be working fine

![localhost_9000_](https://user-images.githubusercontent.com/5106502/47257122-6fd57380-d4bc-11e8-9fa9-9237ec6dd183.png)

**Comment by sijieg** [comment]
@QzSG 
Hello, it was working fine on my main repo but not on my local repo.

I was referring to this part specifically (screenshot below) on the user guide.
![image](https://user-images.githubusercontent.com/35765034/47257313-b4620e80-d4be-11e8-8e0d-8b351ae5feb9.png)

Thanks!

**Comment by QzSG** [comment]
> @QzSG
> Hello, it was working fine on my main repo but not on my local repo.

@sijieg 
I meant I cloned your main repo to my local disk and did the `-repo C:/localrepo` option, the image above was using the local repo way (Filesystem) and not the git url way. Haha

**Comment by sijieg** [comment]
@QzSG 
Oh, it does work for me now when i clone it as well lol. Can't explain why it doesnt work on my original local repo though... Anyway thanks for the input.

@eugenepeh 
Do you want me to close the issue now?

**Comment by eugenepeh** [comment]
@QzSG 

>@sijieg
I meant I cloned your main repo to my local disk and did the -repo C:/localrepo option, the image above was using the local repo way (Filesystem) and not the git url way. Haha

Thanks for helping with the troubleshoot

>@eugenepeh
Do you want me to close the issue now?

Yes please if it has resolved your issue.
