### ISSUE TITLE
ShadowJar not installed in AB3 Gradle

### ISSUE THREAD

**Issue by px1099** [nusCS2113-AY1819S1/forum#75]
In AB4, ShadowJar is already available in `build.gradle`, but that is not the case for AB3. There is no instruction on how to setup ShadowJar into AB3 in the AB3 or AB4 Developer Guide.

**Comment by okkhoy** [comment]
Please see https://github.com/nusCS2113-AY1819S1/forum/issues/76
I created a new announcement to benefit the entire class.
You may choose to close this issue.
