### ISSUE TITLE
Collating Code 

### ISSUE THREAD

**Issue by Psyf** [nusCS2113-AY1819S1/forum#79]
Hi Prof @okkhoy 

Given that we have RepoSense up and running in our repo, is it still necessary to collate our code? 
In other words, I do not understand collate and reposense well enough to understand the differences in their purpose. 

It'd be very helpful if you could clear this up for the team.

**Comment by okkhoy** [comment]
I will clarify this today/tomorrow.
Wait for the announcement! 

Short answer (as posted on slack): 
> As of now no need for collate. However, I want to monitor the situation for one more week before confirming. Reason: Reposense is still beta!

**Comment by Psyf** [comment]
Thanks for the clarification. I'll leave this open till the announcement.

**Comment by Psyf** [comment]
Update: @okkhoy Reposense failed on our repo some time ago (it was working okay when I checked in the morning)

**Comment by okkhoy** [comment]
@Psyf  Can you give additional details? What do you mean by failed?

**Comment by Psyf** [comment]
![chrome_2018-10-30_12-58-12](https://user-images.githubusercontent.com/13702463/47696857-83fb3c80-dc43-11e8-992f-1b5e192c46c5.png)

I'm seeing this on the Reposense Dashboard. 
It had our code/stats in the morning.

**Comment by okkhoy** [comment]
@Psyf 

Reposense is unable to clone your repo.

Check this in your repo:

![image](https://user-images.githubusercontent.com/1023494/47698226-7052d480-dc49-11e8-987a-aba7ede8eeee.png)

The reposense dev team says, cloning fails due to this.

**Comment by Psyf** [comment]
Hi prof, 

I don't understand why these files would break the cloning process, but I've removed them from our repo/master. 

Is there any way I can check whether RepoSense is working or not myself? (Since, from what I understand, the dashboard is only updated periodically)

**Comment by okkhoy** [comment]
You can run reposense on your own, for your repository. Check the instructions [here](https://nuscs2113-ay1819s1.github.io/website/admin/project-w10-mid-v13.html#ensuring-your-code-is-reposense-compatible).

**Comment by Psyf** [comment]
Seems to be working fine now. Thanks!
