### ISSUE TITLE
the all test pass in my local but after i pr the trivs doesnot pass

### ISSUE THREAD

**Issue by clara1234566** [nusCS2113-AY1819S1/forum#82]
the trivs keep showing some error that i donot have in my local 
how to fix it ?

**Comment by clara1234566** [comment]
the test keep failed is addComand system test
editcommand system test
delete command system test
and ui browser panel test

**Comment by okkhoy** [comment]
Can you link to your failing build?

**Comment by clara1234566** [comment]
ok i try run it again

**Comment by clara1234566** [comment]
https://travis-ci.org/CS2113-AY1819S1-T13-4/main/builds/448728344

**Comment by clara1234566** [comment]
hi, Dr Akshay is the error trivs page link

**Comment by okkhoy** [comment]
see if https://github.com/nusCS2113-AY1819S1/forum/issues/62 solutions help. 
When I look through the log, it seems like you are getting NullPointerExceptions 'cos the window doesn't open. In that case, you can try headless tests.

**Comment by clara1234566** [comment]
thank you so much , I solved it alr it passed now

**Comment by okkhoy** [comment]
👍
