### ISSUE TITLE
Travis: Failed to Deploy

### ISSUE THREAD

**Issue by Psyf** [nusCS2113-AY1819S1/forum#83]
Hi Prof @okkhoy 

We don't understand why Travis fails. The build passes. Here's a screenshot of the issue. Do you have any pointers? 

![chrome_2018-10-31_17-43-25](https://user-images.githubusercontent.com/13702463/47779735-cea8b180-dd34-11e8-83cd-af05c9ed3d6b.png)

**Comment by okkhoy** [comment]
Can you give me the link to your build? 
We don't do any CD. I am suspecting, your autopublishing may be failing.

**Comment by Psyf** [comment]
Here is the link: https://travis-ci.org/CS2113-AY1819S1-T09-1/main

**Comment by okkhoy** [comment]
Two things:
1. Your Github token for autopublishing has been revoked/unset/incorrect
2. (from AB dev) the script to generate autopublishing has the execute bit removed accidentally. (Could happen if you are working on a Linux box.) Could this be a regression of #79 ?

**Comment by teojunjie** [comment]
Hi @okkhoy , could it be because of removing the cache of git. When i did that , i had to manually set the execution bits of each .sh

**Comment by teojunjie** [comment]
Basically i did this commands after i did git rm cache.
git update-index --add --chmod=+x build.sh

**Comment by Psyf** [comment]
Yes, It was the execution bit. Thanks Prof!
