### ISSUE TITLE
Configuring Checkstyle-IDEA

### ISSUE THREAD

**Issue by leegengyu** [nusCS2113-AY1819S1/forum#98]
Good afternoon,

I was trying to configure Checkstyle on Intellij, where we are able to see under **Step 4** of [UsingCheckstyle.adoc](https://github.com/nusCS2113-AY1819S1/addressbook-level4/blob/master/docs/UsingCheckstyle.adoc) that the Checkstyle version has to be set to 8.1.

However, there is no version 8.1 found under the available versions of the plugin after installation. The only versions which are closest are 8.9, 8.10.1 and 8.11. Selecting any of these versions will result in the error described below.
![image](https://user-images.githubusercontent.com/35021368/48044292-28422d80-e1c6-11e8-82ba-7d716461b83e.png)

I am unable to import checkstyle.xml as a result, because the plugin will complain that "**The Checkstyle rules file could not be parsed. …​ The file has been blacklisted for 60s**". This problem was addressed at the last part of UsingCheckstyle.adoc - the solution was to ensure that the plugin is configured to the right version, but I am unable to find the right version under the plugin.

Any advice on this matter would be greatly appreciated; Thank you!

**Comment by micklwl** [comment]
Checkstyle 8.1 is below them. Try scrolling down a bit more.
![image](https://user-images.githubusercontent.com/34745754/48044534-5d9b4b00-e1c7-11e8-8a64-44f5ce3a26cd.png)

**Comment by leegengyu** [comment]
Oops, thanks a lot!

**Comment by okkhoy** [comment]
FYI, this will only check against the `checkstyle.xml` you specify. Code formatter (or using automated code formatting) will not bother to honour the checkstyle configuration that you load.
I tried getting this up to make life simple, after numerous attempts gave up 😞 

If someone managed to get the formatter to honour our checkstyle configuration, please post your steps/approach here!

(reopening the issue)
